baseURL = "https://mergex.app/"
languageCode = "en-us"
title = "Merge App"
theme = "merge-apsho"
publishDir = "docs"

# Navigation Bar
[[menu.main]]
    name = "Home"
    url = "#hero"
    weight = 1
[[menu.main]]
    name = "Blog"
    url = "/blog"
    weight = 2

# Footer Sitemap
[[menu.sitemap]]
    name = "Home"
    url = "#"
    weight = 1
[[menu.sitemap]]
    name = "Terms of Service"
    url = "/terms"
    weight = 2
[[menu.sitemap]]
    name = "Privacy Policy"
    url = "/privacy"
    weight = 3
[[menu.sitemap]]
    name = "License"
    url = "/license"
    weight = 4

# Footer Address
[params.address]
email = "sylenthwave@gmail.com"

# Footer Social
[params.social]
facebook = "https://www.facebook.com/pg/staticmania"
twitter = "https://twitter.com/static_mania"
github = "https://github.com/StaticMania"

[params]

# Header
logo = "images/logo.png"
fabFormURL = "https://fabform.io/f/zWMBVeW"
googleAnalytics = "UA-175025671-2"

# Footer
footerTitle = "Get the latest app updates"
copyright1 = "All right reserved"
copyright2 = "Copyright ©  <a href=\"https://staticmania.com/\" target=\"_blank\">Merge App </a> {year}"

#contact
email = "sylenthwave@gmail.com"
